/**
 * Estoque inicial. Todo dado aqui saiu das legendas do próprio Instagram
 * (@usadosdeluxobrasil) em 07/09/2026, e cada foto é a foto de estúdio do
 * mesmo post. Nada foi arredondado nem inventado.
 *
 * A partir daqui quem manda no estoque é a área de gerência (/admin).
 * Para trocar a persistência por um banco, mexa só em lib/estoque.ts.
 */

export type Carro = {
  slug: string;
  marca: string;
  modelo: string;
  versao: string;
  motor: string;
  potencia: number;
  combustivel: string;
  cambio: string;
  tracao: string;
  ano: string;
  km: number;
  preco: number;
  destaques: string[];
  /** Nome do arquivo em public/images/estoque, sem extensão nem tamanho. */
  foto: string;
  /** Dimensão nativa da origem. O QA compara o desenho contra isto, não contra o arquivo exportado. */
  nativa: { w: number; h: number };
  origem: string;
};

export const CARROS_INICIAIS: Carro[] = [
  {
    slug: "bmw-m4-coupe-2016",
    marca: "BMW",
    modelo: "M4 Coupé",
    versao: "Stage 2 AVUS",
    motor: "3.0 Biturbo",
    potencia: 550,
    combustivel: "Gasolina",
    cambio: "DCT de 7 velocidades",
    tracao: "Traseira",
    ano: "15/16",
    km: 49400,
    preco: 359900,
    destaques: [
      "Stage 2 AVUS",
      "Launch Control",
      "Diferencial ativo M",
      "Suspensão Adaptativa M",
      "Bancos esportivos M em couro",
      "Faróis Full LED Adaptativos",
      "Piloto automático",
      "Câmera de ré",
    ],
    foto: "bmw-m4-coupe",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/DcwgmbgD8qW/",
  },
  {
    slug: "range-rover-velar-p340-2021",
    marca: "Land Rover",
    modelo: "Range Rover Velar P340",
    versao: "R-Dynamic",
    motor: "3.0 V6",
    potencia: 340,
    combustivel: "Gasolina",
    cambio: "Automático",
    tracao: "Integral",
    ano: "2021",
    km: 75800,
    preco: 289000,
    destaques: [
      "Teto panorâmico",
      "Bancos em couro",
      "Modos de condução selecionáveis",
      "Sistema de navegação",
      "Apple CarPlay e Android Auto",
      "Porta-malas com abertura elétrica",
      "Sensor de estacionamento dianteiro e traseiro",
      "Partida por botão",
    ],
    foto: "range-rover-velar",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/DcwfqNHD5Nk/",
  },
  {
    slug: "bmw-320i-m-sport-2023",
    marca: "BMW",
    modelo: "320i",
    versao: "M Sport",
    motor: "2.0 Turbo",
    potencia: 184,
    combustivel: "Flex",
    cambio: "Automático",
    tracao: "Traseira",
    ano: "2023",
    km: 45600,
    preco: 264900,
    destaques: [
      "Acabamento exclusivo M Sport",
      "Painel digital",
      "Central multimídia",
      "Faróis em LED",
      "Volante multifuncional",
      "Rodas de liga leve",
    ],
    foto: "bmw-320i-m-sport",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/Dc1Gf3qkY26/",
  },
  {
    slug: "ford-ranger-black-2027",
    marca: "Ford",
    modelo: "Ranger",
    versao: "Black",
    motor: "2.0 Turbo Diesel",
    potencia: 170,
    combustivel: "Diesel",
    cambio: "Automático",
    tracao: "4x4",
    ano: "26/27",
    km: 3000,
    preco: 211000,
    destaques: [
      "Couro parcial",
      "Painel digital",
      "Apple CarPlay e Android Auto",
      "Faróis Full LED",
      "Controle de descida",
      "Capota marítima",
      "Protetor de caçamba",
      "Câmera de ré",
    ],
    foto: "ford-ranger-black",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/Dct5841j7bT/",
  },
  {
    slug: "audi-q3-black-edition-2022",
    marca: "Audi",
    modelo: "Q3",
    versao: "Black Edition S tronic",
    motor: "1.4 TFSI",
    potencia: 150,
    combustivel: "Flex",
    cambio: "S tronic",
    tracao: "Dianteira",
    ano: "21/22",
    km: 57800,
    preco: 177900,
    destaques: [
      "Teto solar",
      "Bancos em couro",
      "Audi Drive Select",
      "Painel digital",
      "Apple CarPlay e Android Auto",
      "Faróis em LED",
      "Luzes diurnas em LED",
      "Piloto automático",
    ],
    foto: "audi-q3-black-edition",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/DcwgDixD8QD/",
  },
  {
    slug: "chevrolet-camaro-ss-2012",
    marca: "Chevrolet",
    modelo: "Camaro",
    versao: "SS",
    motor: "6.2 V8",
    potencia: 406,
    combustivel: "Gasolina",
    cambio: "Automático",
    tracao: "Traseira",
    ano: "12/12",
    km: 99700,
    preco: 176900,
    destaques: [
      "Duplo escapamento",
      "Detalhes esportivos exclusivos SS",
      "Bancos em couro",
      "Piloto automático",
      "Câmera de ré",
      "Rodas de liga leve",
    ],
    foto: "chevrolet-camaro-ss",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/Dcwfahpj0jq/",
  },
  {
    slug: "gac-gs4-elite-hev-2026",
    marca: "GAC",
    modelo: "GS4",
    versao: "Elite HEV",
    motor: "2.0 Aspirado ciclo Atkinson",
    potencia: 235,
    combustivel: "Híbrido",
    cambio: "DHT de 2 marchas",
    tracao: "Dianteira",
    ano: "25/26",
    km: 4200,
    preco: 174900,
    destaques: [
      "Sistema HEV com bateria de 2,1 kWh",
      "14,1 km/l na cidade e 11,8 km/l na estrada pelo Inmetro",
      "Teto solar panorâmico",
      "Painel digital de 12,3 polegadas",
      "Central multimídia de 10,25 polegadas",
      "Câmeras 360º",
      "Frenagem autônoma de emergência",
      "Porta-malas de 638 litros",
    ],
    foto: "gac-gs4-elite-hev",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/Dc1UtCMEYLf/",
  },
  {
    slug: "byd-song-plus-gs-2024",
    marca: "BYD",
    modelo: "Song Plus",
    versao: "GS",
    motor: "1.5 Turbo Híbrida",
    potencia: 235,
    combustivel: "Híbrido",
    cambio: "Automático",
    tracao: "Dianteira",
    ano: "23/24",
    km: 46500,
    preco: 166900,
    destaques: [
      "Sistema híbrido plug-in",
      "Teto solar panorâmico",
      "Câmera 360°",
      "Bancos em couro com ajustes elétricos e aquecimento",
      "Central multimídia com tela giratória",
      "Monitor de ponto cego",
      "Frenagem autônoma de emergência",
      "Piloto automático adaptativo",
    ],
    foto: "byd-song-plus-gs",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/Dct39HyDydx/",
  },
  {
    slug: "chevrolet-s10-lt-2016",
    marca: "Chevrolet",
    modelo: "S10",
    versao: "LT",
    motor: "2.8 Turbo Diesel",
    potencia: 200,
    combustivel: "Diesel",
    cambio: "Automático",
    tracao: "4x4",
    ano: "16/16",
    km: 198000,
    preco: 110900,
    destaques: [
      "Capota marítima",
      "Caçamba ampla",
      "Piloto automático",
      "Câmera de ré",
      "Sensor de estacionamento",
      "Faróis de neblina",
    ],
    foto: "chevrolet-s10-lt",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/Dc331hHAFVX/",
  },
  {
    slug: "fiat-pulse-abarth-270-2023",
    marca: "Fiat",
    modelo: "Pulse",
    versao: "Abarth 270",
    motor: "1.3 Turbo",
    potencia: 185,
    combustivel: "Flex",
    cambio: "Automático",
    tracao: "Dianteira",
    ano: "22/23",
    km: 40900,
    preco: 107900,
    destaques: [
      "Modo de condução esportivo",
      "Faróis em LED",
      "Luzes diurnas em LED",
      "Piloto automático",
      "Câmera de ré",
      "Central multimídia",
    ],
    foto: "fiat-pulse-abarth",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/DczC4X1jxNs/",
  },
  {
    slug: "renault-kardian-evolution-2025",
    marca: "Renault",
    modelo: "Kardian",
    versao: "Evolution",
    motor: "1.0 Turbo",
    potencia: 125,
    combustivel: "Flex",
    cambio: "Automático",
    tracao: "Dianteira",
    ano: "2025",
    km: 49300,
    preco: 89000,
    destaques: [
      "IPVA 2026 pago",
      "Painel digital",
      "Apple CarPlay e Android Auto",
      "Airbags frontais, laterais e de cortina",
      "Câmera de ré",
      "Controle de velocidade de cruzeiro",
    ],
    foto: "renault-kardian",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/Dct7Rygj6AR/",
  },
  {
    slug: "volkswagen-saveiro-robust-2026",
    marca: "Volkswagen",
    modelo: "Saveiro",
    versao: "Robust",
    motor: "1.6 Flex",
    potencia: 116,
    combustivel: "Flex",
    cambio: "Manual de 5 velocidades",
    tracao: "Dianteira",
    ano: "25/26",
    km: 200,
    preco: 83900,
    destaques: [
      "Protetor de caçamba",
      "Capota marítima",
      "Controle de estabilidade",
      "Assistente de partida em rampa",
      "Central multimídia com Bluetooth",
      "Rodas de liga leve",
    ],
    foto: "volkswagen-saveiro-robust",
    nativa: { w: 1440, h: 1800 },
    origem: "https://www.instagram.com/p/Dct4kRKDxku/",
  },
];
