"use client";
import { motion, useReducedMotion } from "motion/react";
import { useState } from "react";

const whats="https://wa.me/5579988043479?text=Ol%C3%A1%2C%20vim%20pelo%20site%20da%20Cl%C3%ADnica%20CAE%20e%20gostaria%20de%20agendar%20um%20atendimento.";
const sinais=[
  ["Audiometria","Quero conferir como estou ouvindo","Avalia a percepção de diferentes sons e ajuda a entender como está a sua audição."],
  ["Impedanciometria","Sinto ouvido tampado ou desconforto","Investiga o funcionamento da orelha média e pode complementar outros exames auditivos."],
  ["Processamento Auditivo Central","Escuto, mas me perco em ambientes com ruído","Observa como o cérebro organiza e interpreta os sons, inclusive a fala em situações desafiadoras."]
];
const exames=[
  ["01","Audiometria","Um retrato da sua percepção auditiva, conduzido com calma e orientação."],
  ["02","Impedanciometria","Uma avaliação objetiva do funcionamento da orelha média."],
  ["03","Processamento Auditivo Central","Uma investigação de como os sons são interpretados."],
  ["04","Consulta fonoaudiológica","O ponto de partida para entender a queixa e definir o cuidado."]
];
function Arrow(){return <svg aria-hidden viewBox="0 0 24 24"><path d="M5 12h13M13 6l6 6-6 6" fill="none" stroke="currentColor" strokeWidth="1.8"/></svg>}
function Mark({small=false}:{small?:boolean}){return <span className={`mark ${small?"small":""}`} aria-hidden>{[1,2,3,4,5].map(n=><i key={n}/>)}</span>}
function Reveal({children,className=""}:{children:React.ReactNode;className?:string}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:32}} whileInView={reduce?undefined:{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.65,ease:[.16,1,.3,1]}}>{children}</motion.div>}

export function CaeSite(){const [ativo,setAtivo]=useState(2);const reduce=useReducedMotion();return <main>
  <header className="header shell"><a className="logo" href="#inicio"><Mark small/><span><strong>CAE</strong><small>Clínica de Audição<br/>e Equilíbrio</small></span></a><nav><a href="#exames">Exames</a><a href="#orientacao">Orientação</a><a href="#contato">Contato</a></nav><a className="header-link" href={whats} target="_blank" rel="noreferrer">Agendar <Arrow/></a></header>
  <section className="hero shell" id="inicio"><div className="hero-copy"><motion.p className="kicker" initial={reduce?false:{opacity:0,y:16}} animate={{opacity:1,y:0}}>Audição e equilíbrio · Aracaju</motion.p><motion.h1 initial={reduce?false:{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.7,ease:[.16,1,.3,1]}}>Ouvir bem muda<br/><em>o jeito de estar</em><br/>no mundo.</motion.h1><div className="hero-bottom"><p>Exames auditivos e acompanhamento fonoaudiológico com orientação clara, do começo ao fim.</p><a className="button" href={whats} target="_blank" rel="noreferrer">Agendar atendimento <Arrow/></a></div></div><motion.div className="hero-visual" initial={reduce?false:{opacity:0,scale:.94}} animate={{opacity:1,scale:1}}><div className="orbit one"/><div className="orbit two"/><div className="orbit three"/><Mark/><span className="note a">escutar</span><span className="note b">compreender</span></motion.div></section>
  <section className="trust"><div className="shell trust-grid"><div><strong>4,8</strong><span>avaliação no Google</span></div><div><strong>+192</strong><span>avaliações publicadas</span></div><p>O cuidado aparece nos detalhes: recepção atenciosa, profissionais cuidadosas e explicações que deixam o exame mais tranquilo.</p></div></section>
  <section className="signals shell" id="orientacao"><Reveal className="intro"><p className="kicker">Mapa de sinais</p><h2>O que trouxe você até aqui?</h2><p>Escolha a frase que mais se aproxima do que você sente. Este recurso orienta, mas não substitui uma avaliação profissional.</p></Reveal><div className="game"><div className="options" role="tablist">{sinais.map((s,i)=><button key={s[0]} role="tab" aria-selected={ativo===i} onClick={()=>setAtivo(i)}><span>0{i+1}</span>{s[1]}</button>)}</div><motion.div className="answer" key={ativo} initial={reduce?false:{opacity:0,x:24}} animate={{opacity:1,x:0}}><p>Um exame que pode ajudar</p><h3>{sinais[ativo][0]}</h3><p>{sinais[ativo][2]}</p><a href={whats} target="_blank" rel="noreferrer">Conversar com a equipe <Arrow/></a></motion.div></div></section>
  <section className="exams" id="exames"><div className="shell"><Reveal className="exams-heading"><p className="kicker">Cuidado em cada frequência</p><h2>Exames para entender antes de decidir.</h2></Reveal><div className="exam-list">{exames.map((e,i)=><motion.article key={e[0]} initial={reduce?false:{opacity:0,y:24}} whileInView={reduce?undefined:{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><span>{e[0]}</span><h3>{e[1]}</h3><p>{e[2]}</p></motion.article>)}</div></div></section>
  <section className="process shell"><Reveal><p className="kicker">Como funciona</p><h2>Você não precisa chegar sabendo o nome do exame.</h2></Reveal><div className="steps">{[["1","Conte o que está acontecendo","Uma mensagem já basta para a equipe orientar o primeiro passo."],["2","Receba a orientação","A clínica confirma o atendimento adequado e informa como se preparar."],["3","Faça o exame com tranquilidade","Cada etapa é explicada com linguagem simples, para adultos e crianças."]].map(s=><div key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></section>
  <section className="quote"><div className="shell quote-grid"><p className="kicker">O que os pacientes percebem</p><Reveal><blockquote>“Atenciosas, cuidadosas e muito profissionais.”</blockquote><p className="quote-note">Síntese de avaliações públicas da clínica no Google.</p></Reveal></div></section>
  <section className="contact shell" id="contato"><div><p className="kicker">Clínica CAE · Aracaju</p><h2>Vamos escutar isso com atenção?</h2></div><div className="contact-info"><p>Av. Gonçalo Prado Rolemberg, 211<br/>Centro Médico José Augusto Barreto, sala 809<br/>São José · Aracaju, SE</p><p>Atendimento de segunda a sexta-feira, mediante agendamento.</p><a className="button coral" href={whats} target="_blank" rel="noreferrer">Falar no WhatsApp <Arrow/></a></div></section>
  <footer><div className="shell footer-inner"><a className="logo" href="#inicio"><Mark small/><span><strong>CAE</strong><small>Clínica de Audição<br/>e Equilíbrio</small></span></a><p>© {new Date().getFullYear()} Clínica CAE</p><a href="https://www.instagram.com/clinicacae/" target="_blank" rel="noreferrer">Instagram ↗</a></div></footer>
</main>}
